# Site Configuration
title: FirstHop
subtitle: Network Engineer & Educator
description: Network engineer, educator, and content creator. Simplifying computer networking concepts for everyone.
author: Dani Issac
email: hello@firsthop.tech
baseurl: "/firsthop"
url: "https://daniissac.github.io"

# Social Links
social:
  github: https://github.com/daniissac
  linkedin: https://linkedin.com/in/daniissac

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
timezone: America/Los_Angeles

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Dani Issac"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Markdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false